<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::group(['middleware' => 'web'], function () {

Route::get('lang/{lang}', ['as'=>'lang.switch', 'uses'=>'LanguageController@switchLang']);

Route::resource('articles', 'ArticleController');

Route::get('/home', 'HomeController@index');

Route::auth();
Route::get('/', function () {
    return view('welcome');
});

Route::get('/hola', function () {
    return view('test/test');
});

});

Route::group(['middleware' => ['web']], function () {
    Route::resource("categories","CategoriesController");// generated by scaffold - Category
    Route::get("categories/category/{categories}/duplicate", ['as' => 'categories.duplicate', 'uses' => 'CategoriesController@duplicate']);// generated by scaffold - Category
    Route::resource("categories","CategoriesController");// generated by scaffold - Category
    Route::get("categories/category/{categories}/duplicate", ['as' => 'categories.duplicate', 'uses' => 'CategoriesController@duplicate']);// generated by scaffold - Category
});
//post Resources
/********************* post ***********************************************/
Route::resource('post','PostController');
Route::post('post/{id}/update','PostController@update');
Route::get('post/{id}/delete','PostController@destroy');
Route::get('post/{id}/deleteMsg','PostController@DeleteMsg');
/********************* post ***********************************************/

//comment Resources
/********************* comment ***********************************************/
Route::resource('comment','CommentController');
Route::post('comment/{id}/update','CommentController@update');
Route::get('comment/{id}/delete','CommentController@destroy');
Route::get('comment/{id}/deleteMsg','CommentController@DeleteMsg');
/********************* comment ***********************************************/
